INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('14027131454', 'Ornela Silvana de Souza Jr.', 'alan.quintana@hotmail.com', 83, 9);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('65068507061', 'Hugo Kevin Cruz', 'sophie.aranda@yahoo.com', 106, 8);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('87244586890', 'Manuela Camacho Furtado', 'violeta.serra@hotmail.com', 90, 9);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('76249721775', 'Natália Dominato Saraiva', 'delatorre.josué@gmail.com', 49, 7);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('96948839571', 'Luciana Luzia Matias Filho', 'joão21@yahoo.com', 69, 4);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('40806249992', 'Pâmela de Souza Cordeiro', 'ivana.uchoa@hotmail.com', 69, 7);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('74364354616', 'Manuel Fábio da Cruz Filho', 'camacho.valentin@yahoo.com', 114, 8);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('17531145534', 'Christian Reis Sobrinho', 'michele.jimenes@hotmail.com', 98, 2);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('29154729354', 'Demian Alonso Montenegro', 'lutero.bruno@yahoo.com', 49, 7);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('12315021710', 'Antonieta Rios', 'tortiz@gmail.com', 83, 6);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('18533945453', 'Natal Dias', 'serna.christian@hotmail.com', 122, 1);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('61085486616', 'Jerônimo Serna Escobar Neto', 'ngodói@hotmail.com', 122, 3);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('21230495735', 'Joaquin Anderson Avila', 'nchaves@gmail.com', 130, 1);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('07736835507', 'Rafael Martines Filho', 'batista.emanuel@hotmail.com', 69, 4);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('90283482755', 'Thalissa Vale Dias', 'ariadna.vale@gmail.com', 37, 2);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('98570733479', 'Giovane Cordeiro Beltrão Filho', 'daragão@gmail.com', 122, 1);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('77962164553', 'Miranda Rafaela Medina Filho', 'joaquin68@hotmail.com', 83, 3);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('86650470414', 'Sofia Mel Garcia Sobrinho', 'noelí85@hotmail.com', 62, 5);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('11488874715', 'Helena Ortega Jr.', 'imarés@yahoo.com', 69, 8);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ('82936607252', 'Agustina Martines Gonçalves Filho', 'santiago.elias@gmail.com', 62, 8);
