INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '14027131454', 'Ornela Silvana de Souza Jr.', 'alan.quintana@hotmail.com', 4, 9);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '65068507061', 'Hugo Kevin Cruz', 'sophie.aranda@yahoo.com', 1, 8);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '87244586890', 'Manuela Camacho Furtado', 'violeta.serra@hotmail.com', 1, 9);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '76249721775', 'Natália Dominato Saraiva', 'delatorre.josué@gmail.com', 1, 7);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '96948839571', 'Luciana Luzia Matias Filho', 'joão21@yahoo.com', 8, 4);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '40806249992', 'Pâmela de Souza Cordeiro', 'ivana.uchoa@hotmail.com', 2, 7);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '74364354616', 'Manuel Fábio da Cruz Filho', 'camacho.valentin@yahoo.com', 7, 8);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '17531145534', 'Christian Reis Sobrinho', 'michele.jimenes@hotmail.com', 8, 2);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '29154729354', 'Demian Alonso Montenegro', 'lutero.bruno@yahoo.com', 8, 7);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '12315021710', 'Antonieta Rios', 'tortiz@gmail.com', 2, 6);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '18533945453', 'Natal Dias', 'serna.christian@hotmail.com', 5, 1);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '61085486616', 'Jerônimo Serna Escobar Neto', 'ngodói@hotmail.com', 6, 3);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '21230495735', 'Joaquin Anderson Avila', 'nchaves@gmail.com', 2, 1);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '07736835507', 'Rafael Martines Filho', 'batista.emanuel@hotmail.com', 8, 4);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '90283482755', 'Thalissa Vale Dias', 'ariadna.vale@gmail.com', 4, 2);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '98570733479', 'Giovane Cordeiro Beltrão Filho', 'daragão@gmail.com', 6, 1);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '77962164553', 'Miranda Rafaela Medina Filho', 'joaquin68@hotmail.com', 7, 3);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '86650470414', 'Sofia Mel Garcia Sobrinho', 'noelí85@hotmail.com', 5, 5);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '11488874715', 'Helena Ortega Jr.', 'imarés@yahoo.com', 2, 8);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '82936607252', 'Agustina Martines Gonçalves Filho', 'santiago.elias@gmail.com', 6, 8);