INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '16.00', 8, 10);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '34.00', 2, 157);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '48.00', 4, 120);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '34.00', 1, 194);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '50.00', 3, 33);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '50.00', 2, 61);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '45.00', 0, 158);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '40.00', 7, 108);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '37.00', 3, 72);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '37.00', 5, 129);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '21.00', 8, 27);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '45.00', 5, 84);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '42.00', 7, 154);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '46.00', 4, 80);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '43.00', 2, 136);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '43.00', 0, 32);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '34.00', 9, 57);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '26.00', 3, 69);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '19.00', 4, 149);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '33.00', 3, 18);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '14.00', 9, 186);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '36.00', 8, 49);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '43.00', 6, 179);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '34.00', 0, 195);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '37.00', 6, 149);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '18.00', 9, 44);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '25.00', 8, 122);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '17.00', 3, 177);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '13.00', 4, 107);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '43.00', 5, 86);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '13.00', 5, 2);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '19.00', 4, 93);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '43.00', 5, 190);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '12.00', 3, 26);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '14.00', 8, 2);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '22.00', 6, 1);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '50.00', 5, 135);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '46.00', 7, 17);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '14.00', 0, 47);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '21.00', 2, 49);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '35.00', 6, 51);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '18.00', 2, 190);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '20.00', 7, 3);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '31.00', 6, 185);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '17.00', 7, 73);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '41.00', 9, 68);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '40.00', 9, 121);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '33.00', 6, 126);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '41.00', 2, 105);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '43.00', 5, 23);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '32.00', 1, 29);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '17.00', 3, 78);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '32.00', 4, 200);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '28.00', 2, 185);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '28.00', 4, 84);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '22.00', 1, 178);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '41.00', 0, 180);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '27.00', 9, 18);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '39.00', 4, 129);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '14.00', 5, 29);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '32.00', 8, 103);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '40.00', 5, 139);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '24.00', 7, 165);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '49.00', 3, 70);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '18.00', 8, 72);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '37.00', 0, 165);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '19.00', 8, 27);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '34.00', 1, 125);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '16.00', 2, 47);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '40.00', 7, 40);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '21.00', 7, 178);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '25.00', 0, 72);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '21.00', 9, 197);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '12.00', 5, 120);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '29.00', 6, 171);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '20.00', 3, 4);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '36.00', 3, 66);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '28.00', 6, 82);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '32.00', 9, 163);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '41.00', 2, 149);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '26.00', 0, 29);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '45.00', 5, 184);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '30.00', 3, 199);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '36.00', 7, 13);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '49.00', 3, 166);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '16.00', 8, 86);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '45.00', 2, 97);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '20.00', 3, 29);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '27.00', 2, 142);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '31.00', 6, 199);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '15.00', 6, 50);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '21.00', 1, 81);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '15.00', 5, 40);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '28.00', 5, 84);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '24.00', 8, 198);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '28.00', 2, 14);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '25.00', 3, 164);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '32.00', 8, 115);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '39.00', 8, 154);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '30.00', 3, 19);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '17.00', 6, 111);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '43.00', 2, 89);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '39.00', 0, 65);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '33.00', 5, 72);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '12.00', 1, 50);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '17.00', 5, 134);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '16.00', 8, 50);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '21.00', 2, 137);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '50.00', 8, 47);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '36.00', 5, 83);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '39.00', 2, 164);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '44.00', 4, 182);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '13.00', 7, 99);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '47.00', 8, 17);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '19.00', 6, 120);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '27.00', 7, 147);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '44.00', 6, 80);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '28.00', 0, 195);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '37.00', 6, 45);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '12.00', 1, 75);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '44.00', 5, 39);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '50.00', 8, 190);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '37.00', 4, 194);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '41.00', 4, 167);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '19.00', 1, 36);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '17.00', 2, 140);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '34.00', 1, 79);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '35.00', 6, 17);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '16.00', 2, 20);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '15.00', 3, 10);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '24.00', 1, 165);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '46.00', 2, 196);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '44.00', 8, 67);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '28.00', 9, 49);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '28.00', 0, 157);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '18.00', 0, 51);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '45.00', 0, 125);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '37.00', 5, 131);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '32.00', 8, 126);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '43.00', 7, 66);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '18.00', 5, 39);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '18.00', 1, 1);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '32.00', 4, 191);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '40.00', 0, 188);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '34.00', 0, 65);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '16.00', 6, 101);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '37.00', 4, 15);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '16.00', 6, 170);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '28.00', 6, 51);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '28.00', 6, 151);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '40.00', 1, 31);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '21.00', 6, 47);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '27.00', 4, 92);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '37.00', 4, 51);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '47.00', 1, 141);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '24.00', 1, 79);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '18.00', 2, 10);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '25.00', 3, 95);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '26.00', 7, 154);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '32.00', 8, 126);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '28.00', 7, 19);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '43.00', 3, 129);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '17.00', 3, 63);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '39.00', 4, 41);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '46.00', 2, 159);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '48.00', 3, 80);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '20.00', 8, 91);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '18.00', 0, 199);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '22.00', 7, 34);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '28.00', 6, 40);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '20.00', 8, 33);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '45.00', 6, 51);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '32.00', 9, 11);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '26.00', 0, 8);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '33.00', 8, 184);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '41.00', 9, 157);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '12.00', 3, 162);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '43.00', 1, 19);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '39.00', 3, 161);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '22.00', 6, 26);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '41.00', 3, 137);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '40.00', 5, 119);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '19.00', 4, 122);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '29.00', 6, 8);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '35.00', 7, 71);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '50.00', 5, 127);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '15.00', 7, 92);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '27.00', 5, 33);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '31.00', 9, 44);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '14.00', 1, 20);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '24.00', 0, 155);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '29.00', 9, 10);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '28.00', 6, 168);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '32.00', 2, 96);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '38.00', 6, 96);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '30.00', 5, 133);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '41.00', 0, 111);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '14.00', 2, 90);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '23.00', 7, 141);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '28.00', 2, 17);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '23.00', 6, 169);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '34.00', 5, 32);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '18.00', 7, 57);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '48.00', 3, 56);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '28.00', 2, 193);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '12.00', 5, 40);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '36.00', 2, 83);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '20.00', 5, 101);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '31.00', 1, 48);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '33.00', 1, 5);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '23.00', 6, 123);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '19.00', 8, 174);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '40.00', 6, 37);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '12.00', 4, 158);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '17.00', 8, 29);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '36.00', 9, 72);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '24.00', 1, 70);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '40.00', 5, 102);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '47.00', 1, 196);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '45.00', 1, 33);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '48.00', 6, 52);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '23.00', 3, 185);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '45.00', 7, 56);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '47.00', 4, 134);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '20.00', 9, 87);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '39.00', 8, 92);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '22.00', 8, 97);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '21.00', 6, 49);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '13.00', 4, 57);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '13.00', 3, 86);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '30.00', 8, 133);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '31.00', 6, 36);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '36.00', 3, 21);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '13.00', 2, 21);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '26.00', 8, 72);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '17.00', 6, 118);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '20.00', 5, 191);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '20.00', 9, 19);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '36.00', 6, 177);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '48.00', 2, 31);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '49.00', 6, 61);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '29.00', 6, 121);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '27.00', 9, 145);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '20.00', 2, 178);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '29.00', 7, 1);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '20.00', 0, 71);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '37.00', 1, 71);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '34.00', 8, 63);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '18.00', 2, 195);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '24.00', 6, 103);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '36.00', 4, 153);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '44.00', 7, 55);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '13.00', 7, 106);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '38.00', 1, 171);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '23.00', 4, 30);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '20.00', 4, 65);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '29.00', 0, 25);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '34.00', 1, 145);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '18.00', 7, 170);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '23.00', 0, 80);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '17.00', 1, 16);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '47.00', 5, 41);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '16.00', 0, 97);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '50.00', 0, 101);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '48.00', 6, 7);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '16.00', 7, 117);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '44.00', 1, 111);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '15.00', 3, 170);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '44.00', 6, 23);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '17.00', 9, 199);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '37.00', 0, 166);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '18.00', 3, 86);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '40.00', 9, 164);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '16.00', 1, 162);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '14.00', 8, 31);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '19.00', 9, 166);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '36.00', 4, 144);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '15.00', 5, 9);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '15.00', 4, 8);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '30.00', 7, 38);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '27.00', 1, 184);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '38.00', 5, 84);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '44.00', 4, 93);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '23.00', 6, 168);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '27.00', 3, 198);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '49.00', 9, 103);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '41.00', 2, 136);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '38.00', 7, 152);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '46.00', 6, 200);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '14.00', 3, 63);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '14.00', 9, 79);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '21.00', 3, 168);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '31.00', 5, 102);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '34.00', 7, 103);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '42.00', 4, 99);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '22.00', 1, 3);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '46.00', 3, 61);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '26.00', 9, 46);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '42.00', 2, 97);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '43.00', 1, 8);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '47.00', 2, 180);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '42.00', 3, 187);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '28.00', 9, 19);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '49.00', 6, 107);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '31.00', 4, 82);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '41.00', 7, 150);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '49.00', 8, 113);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '41.00', 9, 154);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '21.00', 3, 128);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '32.00', 5, 74);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '20.00', 2, 30);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '38.00', 3, 43);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '49.00', 4, 180);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '49.00', 4, 189);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '25.00', 8, 117);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '14.00', 4, 77);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '35.00', 8, 73);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '42.00', 4, 194);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '13.00', 6, 195);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '48.00', 9, 131);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '21.00', 0, 92);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '42.00', 4, 119);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '50.00', 5, 194);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '29.00', 3, 166);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '31.00', 3, 56);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '31.00', 1, 181);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '36.00', 5, 156);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '22.00', 3, 4);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '37.00', 1, 163);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '18.00', 0, 145);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '22.00', 5, 56);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '46.00', 1, 88);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '35.00', 0, 7);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '42.00', 5, 8);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '44.00', 2, 25);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '41.00', 7, 11);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '37.00', 0, 196);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '47.00', 4, 56);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '17.00', 0, 181);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '46.00', 6, 65);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '35.00', 5, 160);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '43.00', 9, 133);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '16.00', 7, 35);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '23.00', 4, 192);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '21.00', 8, 21);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '20.00', 4, 122);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '12.00', 4, 103);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '15.00', 7, 168);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '45.00', 1, 172);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '47.00', 9, 48);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '49.00', 8, 146);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '48.00', 0, 41);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '17.00', 1, 25);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '20.00', 3, 139);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '18.00', 2, 93);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '49.00', 2, 60);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '18.00', 4, 115);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '31.00', 9, 90);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '47.00', 9, 48);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '48.00', 1, 111);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '23.00', 9, 142);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '40.00', 7, 163);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '45.00', 7, 37);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '47.00', 2, 21);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '29.00', 1, 50);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '42.00', 8, 9);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '37.00', 1, 52);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '15.00', 6, 147);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '24.00', 6, 10);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '35.00', 2, 102);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '24.00', 4, 92);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '46.00', 3, 171);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '32.00', 6, 7);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '35.00', 2, 37);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '18.00', 3, 7);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '39.00', 1, 108);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '12.00', 8, 160);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '42.00', 9, 172);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '21.00', 4, 175);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '18.00', 1, 131);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '24.00', 9, 70);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '32.00', 2, 193);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '12.00', 0, 49);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '27.00', 4, 16);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '27.00', 5, 93);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '50.00', 7, 17);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '16.00', 0, 162);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '12.00', 5, 19);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '44.00', 0, 171);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '25.00', 4, 66);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '29.00', 5, 96);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '33.00', 2, 146);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '48.00', 1, 81);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '28.00', 6, 181);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '26.00', 4, 151);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '42.00', 0, 107);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '26.00', 1, 64);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '26.00', 0, 111);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '46.00', 4, 77);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '20.00', 2, 66);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '30.00', 4, 192);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '22.00', 9, 138);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '34.00', 5, 174);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '12.00', 3, 12);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '17.00', 3, 144);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '48.00', 5, 57);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '40.00', 8, 157);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '39.00', 3, 173);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '33.00', 2, 20);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '12.00', 3, 74);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '16.00', 7, 162);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '21.00', 1, 103);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '41.00', 1, 87);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '47.00', 2, 43);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '40.00', 0, 80);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '33.00', 3, 157);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '30.00', 8, 108);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '13.00', 4, 104);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '12.00', 9, 167);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '45.00', 8, 104);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '46.00', 6, 79);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '24.00', 7, 93);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '25.00', 8, 49);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '44.00', 4, 155);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '44.00', 6, 175);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '43.00', 1, 172);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '28.00', 9, 172);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '48.00', 6, 115);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '21.00', 0, 166);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '39.00', 3, 44);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '30.00', 6, 161);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '27.00', 1, 5);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '44.00', 1, 136);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '46.00', 9, 14);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '30.00', 5, 123);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '19.00', 9, 85);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '41.00', 0, 37);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '45.00', 9, 72);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '49.00', 3, 149);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '12.00', 4, 28);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '35.00', 9, 22);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '47.00', 5, 48);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '30.00', 8, 108);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '37.00', 1, 135);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '32.00', 0, 161);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '14.00', 7, 108);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '49.00', 1, 127);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '28.00', 3, 108);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '47.00', 5, 20);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '41.00', 6, 59);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '15.00', 5, 10);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '32.00', 4, 63);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '34.00', 0, 112);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '38.00', 9, 177);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '22.00', 2, 111);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '21.00', 3, 53);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '22.00', 4, 174);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '50.00', 0, 16);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '19.00', 5, 194);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '37.00', 4, 139);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '46.00', 9, 22);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '49.00', 9, 165);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '34.00', 7, 151);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '27.00', 0, 106);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '14.00', 7, 50);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '33.00', 3, 61);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '38.00', 5, 95);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '16.00', 3, 29);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '26.00', 0, 135);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '38.00', 2, 100);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '14.00', 4, 32);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '33.00', 5, 110);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '45.00', 0, 89);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '12.00', 6, 179);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '25.00', 9, 107);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '33.00', 2, 164);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '43.00', 6, 70);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '23.00', 7, 1);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '29.00', 5, 68);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '42.00', 1, 38);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '40.00', 3, 43);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '35.00', 7, 177);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '40.00', 5, 32);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '27.00', 6, 94);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '31.00', 6, 154);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '33.00', 6, 152);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '27.00', 4, 165);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '18.00', 0, 107);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '36.00', 6, 46);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '48.00', 2, 179);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '37.00', 9, 150);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '50.00', 8, 42);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '23.00', 3, 72);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '37.00', 3, 157);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '28.00', 8, 56);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '32.00', 3, 127);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '15.00', 1, 155);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '19.00', 7, 131);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '49.00', 3, 86);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '27.00', 9, 77);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '45.00', 7, 161);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '28.00', 3, 52);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '43.00', 7, 83);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '12.00', 4, 41);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '29.00', 5, 52);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '28.00', 7, 71);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '37.00', 2, 74);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '16.00', 9, 140);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '46.00', 2, 14);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '28.00', 8, 103);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '27.00', 2, 120);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '19.00', 4, 107);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '18.00', 6, 166);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '17.00', 2, 175);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '25.00', 1, 143);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '27.00', 5, 169);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '30.00', 1, 104);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '24.00', 6, 63);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '41.00', 8, 124);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '25.00', 3, 159);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '34.00', 1, 111);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '49.00', 9, 108);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '31.00', 1, 169);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '47.00', 0, 11);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '44.00', 9, 123);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '16.00', 3, 18);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '19.00', 5, 18);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '27.00', 7, 26);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '20.00', 2, 43);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '23.00', 2, 193);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '12.00', 4, 34);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '16.00', 2, 122);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '21.00', 5, 137);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '43.00', 3, 33);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '27.00', 5, 116);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '32.00', 2, 149);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '20.00', 8, 128);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '44.00', 3, 158);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '41.00', 5, 67);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '14.00', 6, 74);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '33.00', 3, 118);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '39.00', 3, 188);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '19.00', 1, 11);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '47.00', 9, 137);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '31.00', 9, 147);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '39.00', 1, 116);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '19.00', 0, 53);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '19.00', 3, 109);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '21.00', 2, 27);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '15.00', 6, 133);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '12.00', 4, 26);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '42.00', 9, 160);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '28.00', 8, 152);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '27.00', 6, 178);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '29.00', 7, 26);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '41.00', 6, 107);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '48.00', 1, 143);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '43.00', 4, 101);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '26.00', 7, 101);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '39.00', 5, 147);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '30.00', 0, 108);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '13.00', 1, 85);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '17.00', 9, 57);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '22.00', 0, 13);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '33.00', 1, 149);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '21.00', 9, 144);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '26.00', 2, 68);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '31.00', 4, 92);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '24.00', 3, 129);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '30.00', 9, 187);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '47.00', 2, 131);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '50.00', 2, 68);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '25.00', 2, 167);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '44.00', 5, 124);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '39.00', 3, 100);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '35.00', 6, 23);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '15.00', 5, 17);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '38.00', 3, 104);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '44.00', 2, 49);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '38.00', 2, 162);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '24.00', 7, 124);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '42.00', 6, 122);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '38.00', 7, 178);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '36.00', 3, 50);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '20.00', 1, 151);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '35.00', 4, 44);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '26.00', 1, 148);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '38.00', 4, 27);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '23.00', 6, 167);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '31.00', 2, 62);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '32.00', 7, 82);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '20.00', 2, 6);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '42.00', 9, 103);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '32.00', 3, 170);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '43.00', 5, 134);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '15.00', 1, 176);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '47.00', 5, 53);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '38.00', 3, 158);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '19.00', 0, 5);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '40.00', 3, 169);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '43.00', 7, 75);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '50.00', 7, 198);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '48.00', 5, 112);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '37.00', 8, 64);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '17.00', 0, 101);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '26.00', 7, 80);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '15.00', 5, 129);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '43.00', 8, 86);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '47.00', 7, 77);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '29.00', 7, 155);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '43.00', 5, 178);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '27.00', 6, 154);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '40.00', 2, 157);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '15.00', 5, 80);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '12.00', 3, 166);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '34.00', 7, 187);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '46.00', 5, 139);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '47.00', 5, 9);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '24.00', 8, 5);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '37.00', 6, 200);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '26.00', 4, 173);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '44.00', 9, 69);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '22.00', 2, 22);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '29.00', 5, 109);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '47.00', 0, 33);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '37.00', 5, 34);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '34.00', 9, 111);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '17.00', 3, 56);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '47.00', 6, 55);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '20.00', 1, 184);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '17.00', 9, 53);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '26.00', 9, 130);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '44.00', 6, 80);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '31.00', 9, 142);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '20.00', 8, 87);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '37.00', 1, 186);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '20.00', 8, 58);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '34.00', 0, 142);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '42.00', 8, 132);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '28.00', 2, 162);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '20.00', 3, 18);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '17.00', 1, 132);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '12.00', 5, 36);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '50.00', 0, 137);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '18.00', 2, 177);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '23.00', 2, 124);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '42.00', 5, 144);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '46.00', 2, 38);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '35.00', 0, 118);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '49.00', 0, 133);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '31.00', 7, 177);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '50.00', 6, 166);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '47.00', 5, 12);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '13.00', 6, 14);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '28.00', 9, 139);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '27.00', 9, 20);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '45.00', 1, 83);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '34.00', 8, 53);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '14.00', 6, 57);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '17.00', 3, 85);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '21.00', 7, 158);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '38.00', 4, 171);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '42.00', 5, 21);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '25.00', 8, 43);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '38.00', 7, 101);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '45.00', 6, 39);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '31.00', 2, 171);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '49.00', 0, 55);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '33.00', 0, 15);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '17.00', 2, 107);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '23.00', 8, 38);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '34.00', 3, 121);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '33.00', 1, 139);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '43.00', 6, 52);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '44.00', 5, 126);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '47.00', 2, 183);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '26.00', 0, 127);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '48.00', 4, 84);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '31.00', 4, 2);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '29.00', 9, 124);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '31.00', 1, 188);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '20.00', 5, 88);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '42.00', 4, 102);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '48.00', 3, 61);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '44.00', 9, 30);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '48.00', 1, 192);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '48.00', 8, 197);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '24.00', 4, 40);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '22.00', 3, 8);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '19.00', 8, 72);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '22.00', 4, 87);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '44.00', 1, 174);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '46.00', 6, 67);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '45.00', 9, 87);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '14.00', 9, 47);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '15.00', 6, 112);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '21.00', 9, 97);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '45.00', 0, 45);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '31.00', 9, 96);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '45.00', 9, 12);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '43.00', 1, 77);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '39.00', 5, 74);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '17.00', 3, 84);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '36.00', 9, 132);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '49.00', 0, 95);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '50.00', 7, 92);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '15.00', 1, 149);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '41.00', 9, 153);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '46.00', 0, 127);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '50.00', 1, 36);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '12.00', 8, 108);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '44.00', 4, 178);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '48.00', 2, 55);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '42.00', 7, 23);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '17.00', 3, 166);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '40.00', 7, 198);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '34.00', 4, 170);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '23.00', 9, 21);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '45.00', 1, 169);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '34.00', 8, 70);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '23.00', 9, 100);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '38.00', 4, 132);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '44.00', 0, 70);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '29.00', 9, 176);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '26.00', 2, 32);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '20.00', 2, 188);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '45.00', 5, 195);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '50.00', 4, 50);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Suco Del Valle', '47.00', 5, 41);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '43.00', 0, 161);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '40.00', 1, 29);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '17.00', 8, 198);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '15.00', 7, 42);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '38.00', 5, 41);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '17.00', 9, 142);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '21.00', 9, 195);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '46.00', 7, 142);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '14.00', 9, 135);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '39.00', 1, 77);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '28.00', 6, 104);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '40.00', 3, 113);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '43.00', 6, 46);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '42.00', 4, 104);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '17.00', 7, 140);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '29.00', 2, 119);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '22.00', 6, 117);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '34.00', 6, 8);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '29.00', 2, 137);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '44.00', 0, 108);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '47.00', 7, 30);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '14.00', 3, 61);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Cerveja Heineken', '28.00', 8, 61);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '38.00', 8, 54);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '32.00', 4, 39);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '32.00', 6, 200);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '40.00', 2, 102);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '25.00', 2, 167);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '14.00', 0, 64);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Whisky Johnnie Walker', '21.00', 2, 150);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '43.00', 1, 136);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '50.00', 0, 67);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Amendoim Elma Chips', '34.00', 7, 80);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '22.00', 0, 173);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '28.00', 7, 195);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '50.00', 2, 39);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '29.00', 0, 14);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '36.00', 7, 68);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '43.00', 6, 58);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Barra de Cereal Nutry', '25.00', 2, 28);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '40.00', 5, 152);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Crystal', '24.00', 2, 97);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '20.00', 1, 121);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '45.00', 1, 28);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '33.00', 2, 179);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '23.00', 2, 33);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '21.00', 3, 23);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '43.00', 1, 155);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '34.00', 3, 154);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '37.00', 4, 96);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '25.00', 1, 188);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '41.00', 2, 168);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Castanhas Agtal', '48.00', 5, 178);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chá Lipton', '14.00', 8, 142);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '34.00', 1, 110);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Sprite', '31.00', 8, 104);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '31.00', 7, 124);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Água Tônica Schweppes', '19.00', 6, 44);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Sanduíche Pronto Seara', '20.00', 8, 1);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '12.00', 6, 139);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Chocolate KitKat', '22.00', 6, 53);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '27.00', 8, 112);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Iogurte Nestlé', '49.00', 3, 84);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Gelatina Royal', '23.00', 7, 102);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Salgadinhos Doritos', '45.00', 5, 45);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Refrigerante Coca-Cola', '28.00', 9, 4);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '18.00', 9, 197);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Biscoitos Oreo', '22.00', 4, 28);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Balas Halls', '39.00', 9, 19);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Mini Pizza Sadia', '42.00', 4, 147);
INSERT INTO PRODUTO_FRIGOBAR (nome, valor, estoque, id_acomodacao) VALUES ('Energético Red Bull', '47.00', 9, 11);
