INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Hotel Vista do Sol', 'Chalé', 'Família', '97235-829', 2348); 
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Refúgio da Montanha', 'Pousada', 'Família', '57912-287', 381);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Oásis do Amanhecer', 'Hotel Fazenda', 'Adultos', '72765-467', 2725);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Pousada Serenidade', 'Pousada', 'Família', '53376-970', 6);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Château de Lumière', 'Resort', 'Adultos', '67334-159', 522);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Hotel Safari Dreams', 'Tradicional', 'Pet-friendly', '21782-188', 1574);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Paraíso das Palmeiras', 'Tradicional', 'Beira-Mar', '20894-558', 964);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Diamante Azul Hotel', 'Tradicional', 'Trabalho', '76588-618', 775);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Ilha do Descanso', 'Resort', 'Beira-Mar', '96706-703', 30);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Vila Tropical Escape', 'Hotel Fazenda', 'Pet-friendly', '25601-957', 561);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Encanto Urbano', 'Tradicional', 'Trabalho', '84241-931', 3);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Floresta Encantada Lodge', 'Chalé', 'Adultos', '64461-574', 305);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Estalagem do Pôr do Sol', 'Pousada', 'Família', '36640-960', 2995);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Grand Harmonia', 'Resort', 'Luxo', '81709-549', 1286);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Jardins do Éden', 'Resort', 'Luxo', '43062-063', 541);

INSERT INTO PARCEIRO (nome, ramo) VALUES ('Vértice 360', 'Esporte');
INSERT INTO PARCEIRO (nome, ramo) VALUES ('Pulsar Ativo', 'Esporte');
INSERT INTO PARCEIRO (nome, ramo) VALUES ('Resonante Harmonia', 'Música');
INSERT INTO PARCEIRO (nome, ramo) VALUES ('Fluxo de Ritmo', 'Dança');
INSERT INTO PARCEIRO (nome, ramo) VALUES ('Sabor e Essência', 'Culinária');
INSERT INTO PARCEIRO (nome, ramo) VALUES ('Galeria Mutações', 'Artes');
INSERT INTO PARCEIRO (nome, ramo) VALUES ('Reflexos Azuis', 'Piscina');
INSERT INTO PARCEIRO (nome, ramo) VALUES ('Mente Crítica', 'Jogos');

INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '14027131454', 'Ornela Silvana de Souza Jr.', 'alan.quintana@hotmail.com', 4, 9);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '65068507061', 'Hugo Kevin Cruz', 'sophie.aranda@yahoo.com', 1, 8);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '87244586890', 'Manuela Camacho Furtado', 'violeta.serra@hotmail.com', 1, 9);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '76249721775', 'Natália Dominato Saraiva', 'delatorre.josué@gmail.com', 1, 7);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '96948839571', 'Luciana Luzia Matias Filho', 'joão21@yahoo.com', 8, 4);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '40806249992', 'Pâmela de Souza Cordeiro', 'ivana.uchoa@hotmail.com', 2, 7);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '74364354616', 'Manuel Fábio da Cruz Filho', 'camacho.valentin@yahoo.com', 7, 8);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '17531145534', 'Christian Reis Sobrinho', 'michele.jimenes@hotmail.com', 8, 2);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '29154729354', 'Demian Alonso Montenegro', 'lutero.bruno@yahoo.com', 8, 7);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '12315021710', 'Antonieta Rios', 'tortiz@gmail.com', 2, 6);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '18533945453', 'Natal Dias', 'serna.christian@hotmail.com', 5, 1);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '61085486616', 'Jerônimo Serna Escobar Neto', 'ngodói@hotmail.com', 6, 3);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '21230495735', 'Joaquin Anderson Avila', 'nchaves@gmail.com', 2, 1);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '07736835507', 'Rafael Martines Filho', 'batista.emanuel@hotmail.com', 8, 4);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '90283482755', 'Thalissa Vale Dias', 'ariadna.vale@gmail.com', 4, 2);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '98570733479', 'Giovane Cordeiro Beltrão Filho', 'daragão@gmail.com', 6, 1);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '77962164553', 'Miranda Rafaela Medina Filho', 'joaquin68@hotmail.com', 7, 3);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '86650470414', 'Sofia Mel Garcia Sobrinho', 'noelí85@hotmail.com', 5, 5);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '11488874715', 'Helena Ortega Jr.', 'imarés@yahoo.com', 2, 8);
INSERT INTO CLIENTE (cpf, nome, email, ponto_fidelidade, visitas) VALUES ( '82936607252', 'Agustina Martines Gonçalves Filho', 'santiago.elias@gmail.com', 6, 8);

INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Aula de Natação', 'Piscina', 5, 60, '2023-06-15', 'Calor', 60, 15, 1, 1);  
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Zumba ao Ar Livre', 'Dança', 10, 50, '2022-11-20', 'Calor', 45, 20, 3, 1);
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Torneio de Futebol', 'Esporte', 8, 40, '2024-03-05', 'Calor', 90, 22, 2, 1);
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Show Acústico', 'Música', 12, 99, '2023-09-18', 'Chuva', 120, 3, 4, 1); 
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Workshop de Gastronomia', 'Culinária', 15, 70, '2024-01-22', 'Frio', 180, 12, 5, 1);
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Aventura de Escalada', 'Radical', 12, 50, '2022-10-10', 'Frio', 150, 10, 1, 1);
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Yoga na Praia', 'Ar livre', 16, 99, '2023-05-25', 'Calor', 60, 30, 4, 1);
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Dança de Salão', 'Dança', 18, 70, '2022-12-12', 'Chuva', 90, 25, 4, 1);
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Cinema ao Ar Livre', 'Teatro', 5, 99, '2024-07-30', 'Calor', 120, 100, 6, 1);
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Canoagem', 'Esporte', 10, 50, '2023-03-15', 'Frio', 120, 12, 2, 1);
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Show de Jazz', 'Música', 16, 99, '2024-04-10', 'Chuva', 120, 40, 7, 1); 
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Treinamento Funcional', 'Esporte', 12, 60, '2023-02-08', 'Frio', 45, 18, 4, 1);
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Curso de Pintura', 'Artes', 8, 70, '2022-09-14', 'Chuva', 90, 15, 6, 1);
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Palestra de Mindfulness', 'Teatro', 18, 70, '2023-11-25', 'Frio', 60, 30, 8, 1);
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Corrida na Trilha', 'Esporte', 10, 40, '2022-06-18', 'Calor', 60, 50, 3, 1);
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Festival Gastronômico', 'Culinária', 16, 99, '2024-05-14', 'Frio', 180, 200, 5, 1);
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Luau na Praia', 'Música', 12, 99, '2023-08-20', 'Calor', 120, 50, 3, 1);
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Oficina de Esculturas', 'Artes', 10, 50, '2022-07-22', 'Chuva', 90, 20, 7, 1);
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Patinação no Gelo', 'Radical', 8, 50, '2024-01-09', 'Frio', 90, 25, 1, 1); 
INSERT INTO ATIVIDADE (nome, tipo, idade_min, idade_max, data_atv, sazonalidade, duracao, capacidade_max, id_parceiro, id_unidade) VALUES ('Dança Folclórica', 'Dança', 12, 70, '2023-10-05', 'Chuva', 60, 30, 4, 1);

INSERT INTO EXTERNA (id_atividade, local, distancia) VALUES (4, 'Casa de Eventos Plaza', 4);
INSERT INTO EXTERNA (id_atividade, local, distancia) VALUES (6, 'Praia dos Ventos', 6);
INSERT INTO EXTERNA (id_atividade, local, distancia) VALUES (10, 'Rio das Ostras', 5);
INSERT INTO EXTERNA (id_atividade, local, distancia) VALUES (11, 'Casa de Eventos Sukuya', 3);
INSERT INTO EXTERNA (id_atividade, local, distancia) VALUES (15, 'Reserva Nacional Arara Azul', 7);
INSERT INTO EXTERNA (id_atividade, local, distancia) VALUES (17, 'Praia das Conchas', 9);
INSERT INTO EXTERNA (id_atividade, local, distancia) VALUES (19, 'Patinação WA', 5);

INSERT INTO MONITOR (cpf, nome, idade, sexo, tipo, telefone) VALUES ('32947699184', 'Aaron Natal Velasques Jr.', 51, 'Masculino', 'Esporte', '11987654321');
INSERT INTO MONITOR (cpf, nome, idade, sexo, tipo, telefone) VALUES ('80398886810', 'Thalissa Faro Gomes', 49, 'Feminino', 'Esporte', '21912345678');
INSERT INTO MONITOR (cpf, nome, idade, sexo, tipo, telefone) VALUES ('94770552441', 'Ricardo Tamoio Jr.', 46, 'Masculino', 'Dança', '31998765432');
INSERT INTO MONITOR (cpf, nome, idade, sexo, tipo, telefone) VALUES ('98759776748', 'Adriano Esteves Branco', 29, 'Masculino', 'Teatro', '41923456789');
INSERT INTO MONITOR (cpf, nome, idade, sexo, tipo, telefone) VALUES ('70425373945', 'Leandro Rezende Abreu Neto', 42, 'Masculino', 'Estudos', '51976543210');
INSERT INTO MONITOR (cpf, nome, idade, sexo, tipo, telefone) VALUES ('19568172624', 'Ziraldo Santacruz', 21, 'Masculino', 'Jogos', '61934567890');
INSERT INTO MONITOR (cpf, nome, idade, sexo, tipo, telefone) VALUES ('12025773762', 'Miranda Duarte Sobrinho', 34, 'Feminino', 'Dança', '71987123456');

INSERT INTO MOTORISTA (cpf, nome, telefone) VALUES ('57238896326', 'Ivana Batista Meireles', '85987654321');
INSERT INTO MOTORISTA (cpf, nome, telefone) VALUES ('77161068065', 'Máximo Rangel Barreto', '92912345678');
INSERT INTO MOTORISTA (cpf, nome, telefone) VALUES ('09836094258', 'Renata Brito', '47998765432');
INSERT INTO MOTORISTA (cpf, nome, telefone) VALUES ('03524087111', 'Manuel Ivan Delgado', '83923456789');
INSERT INTO MOTORISTA (cpf, nome, telefone) VALUES ('41006432851', 'Elias Correia Teles Sobrinho', '63976543210');

INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Pet-Friendly', TRUE, FALSE, '99', 'Check-out até 12h, proibido fumar, pets permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 4, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Pet-Friendly', TRUE, FALSE, '99', 'Check-out até 12h, proibido fumar, pets permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 6, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Quarto', TRUE, FALSE, '99', 'Check-out até 12h, proibido fumar, pets não permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 5, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Pet-Friendly', TRUE, FALSE, '99', 'Check-out até 12h, proibido fumar, pets permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 6, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Quarto', TRUE, FALSE, '99', 'Check-out até 12h, proibido fumar, pets não permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 3, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Quarto', TRUE, FALSE, '99', 'Check-out até 12h, proibido fumar, pets não permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 5, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Suite', TRUE, FALSE, '99', 'Check-out até 12h, proibido fumar, pets não permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 4, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Duplex', TRUE, TRUE, '99', 'Check-out até 12h, proibido fumar, pets não permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 2, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Suite', TRUE, FALSE, '99', 'Check-out até 12h, proibido fumar, pets não permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 7, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Duplex', TRUE, FALSE, '99', 'Check-out até 12h, proibido fumar, pets não permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 10, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Suite', TRUE, FALSE, '99', 'Check-out até 12h, proibido fumar, pets não permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 1, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Triplex', FALSE, TRUE, '99', 'Check-out até 12h, proibido fumar, pets não permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 4, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Duplex', TRUE, TRUE, '99', 'Check-out até 12h, proibido fumar, pets não permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 1, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Suite', FALSE, FALSE, '99', 'Check-out até 12h, proibido fumar, pets não permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 4, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Pet-Friendly', TRUE, TRUE, '99', 'Check-out até 12h, proibido fumar, pets permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 2, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Quarto', FALSE, FALSE, '99', 'Check-out até 12h, proibido fumar, pets não permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 8, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Pet-Friendly', TRUE, FALSE, '99', 'Check-out até 12h, proibido fumar, pets permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 6, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Pet-Friendly', FALSE, TRUE, '99', 'Check-out até 12h, proibido fumar, pets permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 8, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Quarto', TRUE, FALSE, '99', 'Check-out até 12h, proibido fumar, pets não permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 5, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Triplex', TRUE, FALSE, '99', 'Check-out até 12h, proibido fumar, pets não permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 10, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Suite', TRUE, TRUE, '99', 'Check-out até 12h, proibido fumar, pets não permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 8, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Suite', FALSE, FALSE, '99', 'Check-out até 12h, proibido fumar, pets não permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 2, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Suite', TRUE, FALSE, '99', 'Check-out até 12h, proibido fumar, pets não permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 9, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Pet-Friendly', TRUE, FALSE, '99', 'Check-out até 12h, proibido fumar, pets permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 9, 1);
INSERT INTO ACOMODACAO (tipo, status, limpeza, preco, politica_uso, capacidade_max, id_unidade) VALUES ('Duplex', FALSE, TRUE, '99', 'Check-out até 12h, proibido fumar, pets não permitidos, danos serão cobrados, somente hóspedes, itens de frigobar pagos no Check-out, proibido pendurar roupas nas janelas, proibido mudar móveis ou objetos de lugar', 4, 1);

INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('16450.00', '2022-10-03', '2022-10-15', 8, 1);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('6236.00', '2023-05-22', '2023-06-02', 10, 2);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('11505.00', '2022-02-20', '2022-02-28', 1, 3);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('13196.00', '2023-08-25', '2023-09-10', 6, 4);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('5095.00', '2023-02-17', '2023-02-22', 12, 5);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('12370.00', '2022-05-18', '2022-05-30', 15, 6);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('9812.00', '2024-07-30', '2024-07-10', 19, 7);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('10063.00', '2021-04-24', '2021-05-03', 14, 8);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('19157.00', '2023-12-13', '2023-12-25', 1, 9);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('13444.00', '2021-07-12', '2021-07-23', 17, 10);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('12334.00', '2023-06-06', '2023-06-18', 12, 11);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('7412.00', '2021-10-21', '2021-10-28', 3, 12);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('11615.00', '2022-07-19', '2022-07-30', 2, 13);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('1699.00', '2022-06-06', '2022-06-07', 7, 14);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('1002.00', '2023-06-01', '2023-06-02', 14, 15);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('17320.00', '2021-06-17', '2021-07-10', 5, 16);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('2178.00', '2022-05-08', '2022-05-10', 4, 17);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('9622.00', '2021-09-10', '2021-09-28', 11, 18);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('4697.00', '2023-01-15', '2023-01-19', 8, 19);
INSERT INTO RESERVA (valor, per_dt_inicio, per_dt_fim, id_cliente, id_acomodacao) VALUES ('14883.00', '2022-02-02', '2022-02-14', 3, 20);

INSERT INTO HOSPEDE (cpf, id_reserva) VALUES ('12345678901', 4);
INSERT INTO HOSPEDE (cpf, id_reserva) VALUES ('98765432109', 18);
INSERT INTO HOSPEDE (cpf, id_reserva) VALUES ('23456789012', 7);
INSERT INTO HOSPEDE (cpf, id_reserva) VALUES ('45678901234', 9);
INSERT INTO HOSPEDE (cpf, id_reserva) VALUES ('56789012345', 2);

INSERT INTO AVALIA (id_atividade, id_hospede, nota, comentario, data_avaliacao) VALUES (3, 1, 10, 'Show!!', '2024-03-05');
INSERT INTO AVALIA (id_atividade, id_hospede, nota, comentario, data_avaliacao) VALUES (17, 1, 8, 'Muito legal, ótima oportunidade de conhecer novas pessoas', '2023-08-20');
INSERT INTO AVALIA (id_atividade, id_hospede, nota, comentario, data_avaliacao) VALUES (6, 2, 7, 'ótima ideia de atividade, a escalada foi ótima! só um pouco dificil', '2022-10-10');
INSERT INTO AVALIA (id_atividade, id_hospede, nota, comentario, data_avaliacao) VALUES (7, 2, 8, 'Muito legal, adorei', '2023-05-25');
INSERT INTO AVALIA (id_atividade, id_hospede, nota, comentario, data_avaliacao) VALUES (7, 5, 10, 'A atividade de yoga foi excelente! Ambiente calmo e instrutores dedicados.', '2023-05-25');
INSERT INTO AVALIA (id_atividade, id_hospede, nota, comentario, data_avaliacao) VALUES (9, 3, 6, 'O cinema ao ar livre foi uma boa ideia, mas o áudio estava baixo demais.', '2024-07-30');
INSERT INTO AVALIA (id_atividade, id_hospede, nota, comentario, data_avaliacao) VALUES (5, 3, 6, 'A aula de culinária foi divertida, mas senti falta de mais receitas para aprender.', '2024-01-22');
INSERT INTO AVALIA (id_atividade, id_hospede, nota, comentario, data_avaliacao) VALUES (1, 5, 9, 'Aula muito boa', '2023-06-15');
INSERT INTO AVALIA (id_atividade, id_hospede, nota, comentario, data_avaliacao) VALUES (18, 5, 9, 'Adorei a oficina de escultura! Os instrutores eram ótimos e me diverti muito.', '2022-07-22 ');
INSERT INTO AVALIA (id_atividade, id_hospede, nota, comentario, data_avaliacao) VALUES (8, 5, 7, 'A aula de dança foi muito animada, mas gostaria que houvesse mais variedade nas músicas.', '2022-12-12 ');