INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('feijoada', '65.30', 158, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('fruta fresca (mamão', '70.78', 184, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bolinho de chuva', '75.73', 185, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('escondidinho de carne seca', '36.69', 85, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vatapá', '65.31', 173, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('peixe assado com farofa', '73.74', 128, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bolo de fubá', '71.56', 199, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('costela assada', '54.21', 67, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pirão de peixe', '28.00', 164, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('goiabada com queijo', '68.88', 97, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('carne de sol com purê de abób', '20.56', 132, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão de queijo', '65.12', 57, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('churrasco com pão de alho', '30.71', 151, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('baião de dois', '63.22', 80, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mingau de aveia', '18.54', 153, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('arroz com pequi', '53.58', 124, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pamonha assada', '75.54', 153, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de legumes', '31.06', 122, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('café preto', '27.23', 120, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('acarajé', '45.01', 70, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('banana)', '48.74', 168, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('galinhada', '45.03', 141, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão francês com manteiga', '28.96', 93, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('feijão tropeiro', '48.02', 174, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caldo de mandioca', '65.02', 156, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('camarão na moranga', '36.02', 125, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('moqueca de peixe', '18.65', 155, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tapioca com queijo', '51.20', 104, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cuscuz com manteiga', '46.58', 117, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pinga com mel', '31.33', 177, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('guaraná natural', '18.38', 163, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vinho colonial', '8.28', 69, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cachaça pura', '10.59', 134, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caipirinha', '21.02', 175, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('batida de coco', '27.90', 159, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de laranja', '18.45', 136, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água de coco', '18.40', 149, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de melancia', '21.48', 126, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caldo de cana', '26.59', 189, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('batida de maracujá', '17.78', 196, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água', '32.83', 176, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('licor de jabuticaba', '21.94', 81, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caipiroska de morango', '32.09', 81, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá de capim-limão', '23.84', 159, 18);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('feijoada', '65.30', 158, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('fruta fresca (mamão', '70.78', 184, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bolinho de chuva', '75.73', 185, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('escondidinho de carne seca', '36.69', 85, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vatapá', '65.31', 173, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('peixe assado com farofa', '73.74', 128, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bolo de fubá', '71.56', 199, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('costela assada', '54.21', 67, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pirão de peixe', '28.00', 164, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('goiabada com queijo', '68.88', 97, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('carne de sol com purê de abób', '20.56', 132, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão de queijo', '65.12', 57, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('churrasco com pão de alho', '30.71', 151, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('baião de dois', '63.22', 80, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mingau de aveia', '18.54', 153, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('arroz com pequi', '53.58', 124, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pamonha assada', '75.54', 153, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de legumes', '31.06', 122, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('café preto', '27.23', 120, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('acarajé', '45.01', 70, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('banana)', '48.74', 168, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('galinhada', '45.03', 141, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão francês com manteiga', '28.96', 93, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('feijão tropeiro', '48.02', 174, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caldo de mandioca', '65.02', 156, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('camarão na moranga', '36.02', 125, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('moqueca de peixe', '18.65', 155, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tapioca com queijo', '51.20', 104, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cuscuz com manteiga', '46.58', 117, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pinga com mel', '31.33', 177, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('guaraná natural', '18.38', 163, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vinho colonial', '8.28', 69, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cachaça pura', '10.59', 134, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caipirinha', '21.02', 175, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('batida de coco', '27.90', 159, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de laranja', '18.45', 136, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água de coco', '18.40', 149, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de melancia', '21.48', 126, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caldo de cana', '26.59', 189, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('batida de maracujá', '17.78', 196, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água', '32.83', 176, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('licor de jabuticaba', '21.94', 81, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caipiroska de morango', '32.09', 81, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá de capim-limão', '23.84', 159, 19);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('feijoada', '65.30', 158, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('fruta fresca (mamão', '70.78', 184, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bolinho de chuva', '75.73', 185, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('escondidinho de carne seca', '36.69', 85, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vatapá', '65.31', 173, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('peixe assado com farofa', '73.74', 128, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bolo de fubá', '71.56', 199, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('costela assada', '54.21', 67, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pirão de peixe', '28.00', 164, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('goiabada com queijo', '68.88', 97, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('carne de sol com purê de abób', '20.56', 132, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão de queijo', '65.12', 57, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('churrasco com pão de alho', '30.71', 151, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('baião de dois', '63.22', 80, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mingau de aveia', '18.54', 153, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('arroz com pequi', '53.58', 124, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pamonha assada', '75.54', 153, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de legumes', '31.06', 122, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('café preto', '27.23', 120, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('acarajé', '45.01', 70, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('banana)', '48.74', 168, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('galinhada', '45.03', 141, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão francês com manteiga', '28.96', 93, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('feijão tropeiro', '48.02', 174, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caldo de mandioca', '65.02', 156, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('camarão na moranga', '36.02', 125, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('moqueca de peixe', '18.65', 155, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tapioca com queijo', '51.20', 104, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cuscuz com manteiga', '46.58', 117, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pinga com mel', '31.33', 177, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('guaraná natural', '18.38', 163, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vinho colonial', '8.28', 69, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cachaça pura', '10.59', 134, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caipirinha', '21.02', 175, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('batida de coco', '27.90', 159, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de laranja', '18.45', 136, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água de coco', '18.40', 149, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de melancia', '21.48', 126, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caldo de cana', '26.59', 189, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('batida de maracujá', '17.78', 196, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água', '32.83', 176, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('licor de jabuticaba', '21.94', 81, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caipiroska de morango', '32.09', 81, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá de capim-limão', '23.84', 159, 22);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('feijoada', '65.30', 158, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('fruta fresca (mamão', '70.78', 184, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bolinho de chuva', '75.73', 185, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('escondidinho de carne seca', '36.69', 85, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vatapá', '65.31', 173, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('peixe assado com farofa', '73.74', 128, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bolo de fubá', '71.56', 199, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('costela assada', '54.21', 67, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pirão de peixe', '28.00', 164, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('goiabada com queijo', '68.88', 97, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('carne de sol com purê de abób', '20.56', 132, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão de queijo', '65.12', 57, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('churrasco com pão de alho', '30.71', 151, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('baião de dois', '63.22', 80, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mingau de aveia', '18.54', 153, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('arroz com pequi', '53.58', 124, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pamonha assada', '75.54', 153, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de legumes', '31.06', 122, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('café preto', '27.23', 120, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('acarajé', '45.01', 70, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('banana)', '48.74', 168, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('galinhada', '45.03', 141, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão francês com manteiga', '28.96', 93, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('feijão tropeiro', '48.02', 174, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caldo de mandioca', '65.02', 156, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('camarão na moranga', '36.02', 125, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('moqueca de peixe', '18.65', 155, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tapioca com queijo', '51.20', 104, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cuscuz com manteiga', '46.58', 117, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pinga com mel', '31.33', 177, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('guaraná natural', '18.38', 163, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vinho colonial', '8.28', 69, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cachaça pura', '10.59', 134, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caipirinha', '21.02', 175, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('batida de coco', '27.90', 159, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de laranja', '18.45', 136, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água de coco', '18.40', 149, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de melancia', '21.48', 126, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caldo de cana', '26.59', 189, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('batida de maracujá', '17.78', 196, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água', '32.83', 176, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('licor de jabuticaba', '21.94', 81, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caipiroska de morango', '32.09', 81, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá de capim-limão', '23.84', 159, 27);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('feijoada', '65.30', 158, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('fruta fresca (mamão', '70.78', 184, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bolinho de chuva', '75.73', 185, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('escondidinho de carne seca', '36.69', 85, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vatapá', '65.31', 173, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('peixe assado com farofa', '73.74', 128, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bolo de fubá', '71.56', 199, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('costela assada', '54.21', 67, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pirão de peixe', '28.00', 164, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('goiabada com queijo', '68.88', 97, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('carne de sol com purê de abób', '20.56', 132, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão de queijo', '65.12', 57, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('churrasco com pão de alho', '30.71', 151, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('baião de dois', '63.22', 80, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mingau de aveia', '18.54', 153, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('arroz com pequi', '53.58', 124, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pamonha assada', '75.54', 153, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de legumes', '31.06', 122, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('café preto', '27.23', 120, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('acarajé', '45.01', 70, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('banana)', '48.74', 168, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('galinhada', '45.03', 141, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão francês com manteiga', '28.96', 93, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('feijão tropeiro', '48.02', 174, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caldo de mandioca', '65.02', 156, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('camarão na moranga', '36.02', 125, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('moqueca de peixe', '18.65', 155, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tapioca com queijo', '51.20', 104, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cuscuz com manteiga', '46.58', 117, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pinga com mel', '31.33', 177, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('guaraná natural', '18.38', 163, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vinho colonial', '8.28', 69, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cachaça pura', '10.59', 134, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caipirinha', '21.02', 175, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('batida de coco', '27.90', 159, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de laranja', '18.45', 136, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água de coco', '18.40', 149, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de melancia', '21.48', 126, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caldo de cana', '26.59', 189, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('batida de maracujá', '17.78', 196, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água', '32.83', 176, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('licor de jabuticaba', '21.94', 81, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('caipiroska de morango', '32.09', 81, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá de capim-limão', '23.84', 159, 30);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de cenoura', '53.14', 85, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('leite batido com frutas', '60.92', 114, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tostadas', '49.41', 184, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('jamón com pão', '79.15', 168, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('conejo al ajillo', '76.16', 86, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('empanada gallega', '18.16', 113, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de laranja', '39.56', 98, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tortilla de patatas', '38.35', 137, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('café expresso', '16.47', 136, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('café com leche', '32.55', 50, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('calamares fritos', '75.17', 80, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('arroz negro', '65.42', 89, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('smoothie de frutas', '53.41', 127, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tortilla española', '55.56', 121, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água', '67.03', 116, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chocolate quente', '78.56', 149, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água com gás', '16.48', 85, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('gazpacho', '12.40', 84, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de ameixa', '49.24', 111, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de pêssego', '22.95', 162, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('albóndigas', '47.73', 113, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('estofado de carne', '25.88', 98, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('queijo manchego', '55.17', 65, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água de coco', '26.85', 198, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('horchata', '53.38', 151, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá gelado', '42.15', 108, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bacalao al pil-pil', '15.63', 95, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mejillones en escabeche', '31.81', 128, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bizcocho de limón', '20.56', 125, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('infusão de ervas', '35.70', 174, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água com gás', '13.14', 120, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá preto', '28.36', 195, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('limonada', '15.22', 120, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vinho branco', '17.71', 187, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sidra asturiana', '9.54', 163, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá gelado', '27.44', 165, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vinho de Jerez', '20.84', 128, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('smoothie de frutas', '8.41', 188, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('café expresso', '31.25', 92, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('leite batido com frutas', '9.20', 67, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('licor de café', '13.01', 174, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de laranja', '13.97', 197, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá verde', '8.22', 114, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chocolate quente', '30.92', 179, 31);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('infusão de ervas', '16.26', 103, 31); 
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' quiche lorraine', '50.84', 63, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' madeleines', '78.51', 181, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' fricassée de poulet', '61.65', 65, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' steak tartare', '53.15', 163, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' entrecôte com molho béarnaise', '74.41', 197, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' canard à lorange', '42.82', 183, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' moules marinières', '69.58', 139, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' soupe à l\oignon', '49.36', 176, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' chateaubriand', '76.43', 174, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' steak au poivre', '32.69', 55, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' coq au vin', '18.08', 62, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' brandade de morue', '22.06', 82, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' salade niçoise', '50.05', 56, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' ratatouille', '41.07', 140, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' crepe de morango', '23.72', 184, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' vol-au-vent', '53.85', 106, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' magret de canard', '23.60', 179, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' tarte au citron', '55.66', 85, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' pain au chocolat', '50.29', 179, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' cassoulet', '42.41', 119, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' boeuf bourguignon', '14.49', 115, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' brioche', '56.38', 61, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' bouillabaisse', '71.67', 127, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('croissant', '60.64', 83, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' omelette aux fines herbes', '18.73', 76, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' escargot', '21.57', 86, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' navarin dagneau', '47.78', 140, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' baguette com manteiga', '68.16', 131, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' pain perdu', '61.28', 117, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' armagnac', '33.90', 129, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' suco de pera', '31.04', 77, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' chá de camomila', '13.00', 173, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' grand marnier', '13.59', 174, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' suco de cranberry', '27.44', 164, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' pastis', '32.22', 167, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' suco de maçã', '27.12', 97, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' smoothie de frutas vermelhas', '27.90', 119, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' leite fresco', '30.75', 125, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' suco de laranja', '17.95', 119, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' kombucha de limão', '16.79', 115, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' café preto', '25.52', 122, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' suco de toranja', '27.28', 199, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' vinho tinto', '34.46', 179, 17);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' champanhe', '25.20', 131, 17); 
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' quiche lorraine', '50.84', 63, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' madeleines', '78.51', 181, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' fricassée de poulet', '61.65', 65, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' steak tartare', '53.15', 163, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' entrecôte com molho béarnaise', '74.41', 197, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' canard à lorange', '42.82', 183, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' moules marinières', '69.58', 139, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' soupe à l\oignon', '49.36', 176, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' chateaubriand', '76.43', 174, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' steak au poivre', '32.69', 55, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' coq au vin', '18.08', 62, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' brandade de morue', '22.06', 82, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' salade niçoise', '50.05', 56, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' ratatouille', '41.07', 140, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' crepe de morango', '23.72', 184, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' vol-au-vent', '53.85', 106, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' magret de canard', '23.60', 179, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' tarte au citron', '55.66', 85, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' pain au chocolat', '50.29', 179, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' cassoulet', '42.41', 119, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' boeuf bourguignon', '14.49', 115, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' brioche', '56.38', 61, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' bouillabaisse', '71.67', 127, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('croissant', '60.64', 83, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' omelette aux fines herbes', '18.73', 76, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' escargot', '21.57', 86, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' navarin dagneau', '47.78', 140, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' baguette com manteiga', '68.16', 131, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' pain perdu', '61.28', 117, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' armagnac', '33.90', 129, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' suco de pera', '31.04', 77, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' chá de camomila', '13.00', 173, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' grand marnier', '13.59', 174, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' suco de cranberry', '27.44', 164, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' pastis', '32.22', 167, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' suco de maçã', '27.12', 97, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' smoothie de frutas vermelhas', '27.90', 119, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' leite fresco', '30.75', 125, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' suco de laranja', '17.95', 119, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' kombucha de limão', '16.79', 115, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' café preto', '25.52', 122, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' suco de toranja', '27.28', 199, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' vinho tinto', '34.46', 179, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES (' champanhe', '25.20', 131, 24);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tiramisu', '43.87', 157, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('penne allarrabbiata', '42.92', 62, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cappuccino', '71.47', 165, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tagliatelle bolognese', '76.35', 94, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ravioli de queijo', '71.23', 67, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('peixe assado com ervas', '22.25', 107, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('taralli', '79.74', 158, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('lasanha', '61.76', 193, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ossobuco', '52.88', 126, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cordeiro assado', '76.17', 149, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa minestrone', '56.00', 149, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('focaccia', '67.41', 65, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão com nutella', '72.73', 102, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cornetto', '60.96', 177, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sfogliatella', '50.94', 124, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('risotto de frutos do mar', '58.18', 87, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ricotta com mel', '56.48', 137, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('gnocchi al pesto', '40.47', 126, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('polenta', '26.89', 66, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bruschetta', '60.22', 95, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pizza margherita', '34.99', 56, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('carpaccio', '62.67', 117, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ensalada caprese', '69.23', 173, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão ciabatta', '53.37', 151, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('saltimbocca', '15.28', 88, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('risotto milanese', '22.57', 55, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('panna cotta', '71.17', 67, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('brioche com café', '35.82', 132, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('spaghetti carbonara', '66.23', 125, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água com gás', '27.16', 84, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('negroni', '32.97', 78, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chocolate quente', '34.39', 190, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de pera', '17.68', 54, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água', '21.38', 69, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água tônica', '16.17', 133, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá gelado de limão', '34.22', 200, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('campari', '31.72', 90, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('smoothie de frutas vermelhas', '18.65', 141, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de abacaxi', '9.87', 112, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vermute rosso', '10.17', 119, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('infusão de ervas', '17.38', 172, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de maçã', '33.06', 50, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vinho tinto', '33.53', 60, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('grappa', '20.03', 102, 16);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tiramisu', '43.87', 157, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('penne allarrabbiata', '42.92', 62, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cappuccino', '71.47', 165, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tagliatelle bolognese', '76.35', 94, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ravioli de queijo', '71.23', 67, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('peixe assado com ervas', '22.25', 107, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('taralli', '79.74', 158, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('lasanha', '61.76', 193, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ossobuco', '52.88', 126, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cordeiro assado', '76.17', 149, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa minestrone', '56.00', 149, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('focaccia', '67.41', 65, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão com nutella', '72.73', 102, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cornetto', '60.96', 177, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sfogliatella', '50.94', 124, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('risotto de frutos do mar', '58.18', 87, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ricotta com mel', '56.48', 137, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('gnocchi al pesto', '40.47', 126, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('polenta', '26.89', 66, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bruschetta', '60.22', 95, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pizza margherita', '34.99', 56, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('carpaccio', '62.67', 117, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ensalada caprese', '69.23', 173, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão ciabatta', '53.37', 151, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('saltimbocca', '15.28', 88, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('risotto milanese', '22.57', 55, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('panna cotta', '71.17', 67, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('brioche com café', '35.82', 132, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('spaghetti carbonara', '66.23', 125, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água com gás', '27.16', 84, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('negroni', '32.97', 78, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chocolate quente', '34.39', 190, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de pera', '17.68', 54, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água', '21.38', 69, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água tônica', '16.17', 133, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá gelado de limão', '34.22', 200, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('campari', '31.72', 90, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('smoothie de frutas vermelhas', '18.65', 141, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de abacaxi', '9.87', 112, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vermute rosso', '10.17', 119, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('infusão de ervas', '17.38', 172, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de maçã', '33.06', 50, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vinho tinto', '33.53', 60, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('grappa', '20.03', 102, 21);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tiramisu', '43.87', 157, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('penne allarrabbiata', '42.92', 62, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cappuccino', '71.47', 165, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tagliatelle bolognese', '76.35', 94, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ravioli de queijo', '71.23', 67, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('peixe assado com ervas', '22.25', 107, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('taralli', '79.74', 158, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('lasanha', '61.76', 193, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ossobuco', '52.88', 126, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cordeiro assado', '76.17', 149, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa minestrone', '56.00', 149, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('focaccia', '67.41', 65, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão com nutella', '72.73', 102, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cornetto', '60.96', 177, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sfogliatella', '50.94', 124, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('risotto de frutos do mar', '58.18', 87, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ricotta com mel', '56.48', 137, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('gnocchi al pesto', '40.47', 126, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('polenta', '26.89', 66, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bruschetta', '60.22', 95, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pizza margherita', '34.99', 56, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('carpaccio', '62.67', 117, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ensalada caprese', '69.23', 173, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão ciabatta', '53.37', 151, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('saltimbocca', '15.28', 88, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('risotto milanese', '22.57', 55, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('panna cotta', '71.17', 67, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('brioche com café', '35.82', 132, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('spaghetti carbonara', '66.23', 125, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água com gás', '27.16', 84, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('negroni', '32.97', 78, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chocolate quente', '34.39', 190, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de pera', '17.68', 54, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água', '21.38', 69, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água tônica', '16.17', 133, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá gelado de limão', '34.22', 200, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('campari', '31.72', 90, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('smoothie de frutas vermelhas', '18.65', 141, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de abacaxi', '9.87', 112, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vermute rosso', '10.17', 119, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('infusão de ervas', '17.38', 172, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de maçã', '33.06', 50, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vinho tinto', '33.53', 60, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('grappa', '20.03', 102, 29);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tiramisu', '43.87', 157, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('penne allarrabbiata', '42.92', 62, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cappuccino', '71.47', 165, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tagliatelle bolognese', '76.35', 94, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ravioli de queijo', '71.23', 67, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('peixe assado com ervas', '22.25', 107, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('taralli', '79.74', 158, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('lasanha', '61.76', 193, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ossobuco', '52.88', 126, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cordeiro assado', '76.17', 149, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa minestrone', '56.00', 149, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('focaccia', '67.41', 65, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão com nutella', '72.73', 102, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cornetto', '60.96', 177, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sfogliatella', '50.94', 124, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('risotto de frutos do mar', '58.18', 87, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ricotta com mel', '56.48', 137, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('gnocchi al pesto', '40.47', 126, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('polenta', '26.89', 66, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bruschetta', '60.22', 95, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pizza margherita', '34.99', 56, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('carpaccio', '62.67', 117, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ensalada caprese', '69.23', 173, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão ciabatta', '53.37', 151, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('saltimbocca', '15.28', 88, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('risotto milanese', '22.57', 55, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('panna cotta', '71.17', 67, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('brioche com café', '35.82', 132, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('spaghetti carbonara', '66.23', 125, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água com gás', '27.16', 84, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('negroni', '32.97', 78, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chocolate quente', '34.39', 190, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de pera', '17.68', 54, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água', '21.38', 69, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água tônica', '16.17', 133, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá gelado de limão', '34.22', 200, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('campari', '31.72', 90, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('smoothie de frutas vermelhas', '18.65', 141, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de abacaxi', '9.87', 112, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vermute rosso', '10.17', 119, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('infusão de ervas', '17.38', 172, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de maçã', '33.06', 50, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('vinho tinto', '33.53', 60, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('grappa', '20.03', 102, 32);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('curry goat', '29.87', 78, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão coco', '67.58', 105, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('steamed fish', '74.80', 110, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bammy', '32.42', 187, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('frango ensopado', '26.48', 157, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mingau de milho', '77.83', 83, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('curry de vegetais', '39.17', 129, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('banana cozida com carne', '27.39', 134, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('johnnycakes', '41.14', 50, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mingau de banana', '60.81', 152, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de carne de porco', '62.65', 159, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('escovitch fish', '41.21', 62, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('curry de frutos do mar', '29.94', 110, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de ervilha vermelha', '69.87', 197, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('jerk chicken', '61.57', 136, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de abóbora', '26.42', 62, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ackee and saltfish', '29.39', 195, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pepper pot soup', '34.71', 197, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('brown stew chicken', '62.67', 161, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pão de banana frito com camar', '72.88', 199, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('plantains fritos', '50.75', 114, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('festival', '16.27', 103, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('jerk pork', '66.81', 193, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('oxtail stew', '15.54', 90, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('patties jamaicanas', '43.09', 124, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('run down', '53.99', 143, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('callaloo', '51.52', 113, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('rice and peas', '57.32', 159, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('camarão ao coco', '38.23', 53, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('limonada', '15.12', 141, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mojito jamaicano', '20.38', 139, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá de ervas', '13.56', 63, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de guava', '28.38', 136, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água de coco', '10.34', 117, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá de hibisco', '11.69', 75, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de beterraba', '19.94', 100, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('rum cream', '19.57', 62, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('dragon stout', '8.08', 56, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('rum punch', '18.79', 198, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('rum envelhecido', '33.01', 138, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de manga', '34.02', 78, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('red stripe (cerveja)', '21.64', 128, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de melancia', '13.86', 160, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('leite maltado', '10.91', 175, 15);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá verde', '18.12', 148, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('curry japonês', '58.62', 163, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tofu', '71.48', 186, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('udon', '78.22', 139, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tempurá', '32.15', 190, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('okonomiyaki', '40.09', 107, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('natto', '49.11', 113, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sashimi', '14.01', 119, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('onigiri', '19.65', 78, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sukiyaki', '24.78', 83, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('peixe grelhado com molho teri', '17.39', 62, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ameixa umeboshi', '27.90', 164, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('takoyaki', '65.84', 137, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tonkatsu', '68.28', 67, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de tofu', '24.13', 165, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tamagoyaki (omelete japonesa)', '53.69', 167, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de soba', '58.35', 93, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chawanmushi', '31.94', 145, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('peixe grelhado', '36.69', 93, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('gohan (arroz branco)', '21.09', 59, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de missô', '35.83', 177, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('katsudon', '41.73', 62, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('shabu-shabu', '64.95', 77, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('yakiniku', '75.41', 90, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('algas nori', '22.69', 184, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ramen', '71.56', 184, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sushi', '37.55', 52, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bento box completo', '45.37', 194, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('gyudon', '52.92', 188, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('kombucha de gengibre', '12.18', 117, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('coquetel de lichia', '13.39', 118, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água', '30.46', 153, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água com gás', '18.69', 91, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('shochu com água quente', '31.43', 80, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá preto', '27.36', 152, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('leite de soja', '18.85', 66, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('saquê', '14.26', 165, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de ameixa japonesa', '34.55', 68, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de laranja', '27.15', 94, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de manga', '18.94', 131, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('saquê doce', '25.50', 136, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cerveja artesanal japonesa', '20.11', 153, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá de hortelã', '9.77', 52, 13);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá verde', '18.12', 148, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('curry japonês', '58.62', 163, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tofu', '71.48', 186, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('udon', '78.22', 139, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tempurá', '32.15', 190, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('okonomiyaki', '40.09', 107, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('natto', '49.11', 113, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sashimi', '14.01', 119, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('onigiri', '19.65', 78, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sukiyaki', '24.78', 83, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('peixe grelhado com molho teri', '17.39', 62, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ameixa umeboshi', '27.90', 164, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('takoyaki', '65.84', 137, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tonkatsu', '68.28', 67, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de tofu', '24.13', 165, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tamagoyaki (omelete japonesa)', '53.69', 167, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de soba', '58.35', 93, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chawanmushi', '31.94', 145, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('peixe grelhado', '36.69', 93, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('gohan (arroz branco)', '21.09', 59, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de missô', '35.83', 177, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('katsudon', '41.73', 62, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('shabu-shabu', '64.95', 77, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('yakiniku', '75.41', 90, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('algas nori', '22.69', 184, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ramen', '71.56', 184, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sushi', '37.55', 52, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bento box completo', '45.37', 194, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('gyudon', '52.92', 188, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('kombucha de gengibre', '12.18', 117, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('coquetel de lichia', '13.39', 118, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água', '30.46', 153, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água com gás', '18.69', 91, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('shochu com água quente', '31.43', 80, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá preto', '27.36', 152, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('leite de soja', '18.85', 66, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('saquê', '14.26', 165, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de ameixa japonesa', '34.55', 68, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de laranja', '27.15', 94, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de manga', '18.94', 131, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('saquê doce', '25.50', 136, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cerveja artesanal japonesa', '20.11', 153, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá de hortelã', '9.77', 52, 14);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá verde', '18.12', 148, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('curry japonês', '58.62', 163, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tofu', '71.48', 186, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('udon', '78.22', 139, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tempurá', '32.15', 190, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('okonomiyaki', '40.09', 107, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('natto', '49.11', 113, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sashimi', '14.01', 119, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('onigiri', '19.65', 78, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sukiyaki', '24.78', 83, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('peixe grelhado com molho teri', '17.39', 62, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ameixa umeboshi', '27.90', 164, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('takoyaki', '65.84', 137, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tonkatsu', '68.28', 67, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de tofu', '24.13', 165, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tamagoyaki (omelete japonesa)', '53.69', 167, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de soba', '58.35', 93, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chawanmushi', '31.94', 145, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('peixe grelhado', '36.69', 93, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('gohan (arroz branco)', '21.09', 59, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de missô', '35.83', 177, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('katsudon', '41.73', 62, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('shabu-shabu', '64.95', 77, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('yakiniku', '75.41', 90, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('algas nori', '22.69', 184, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ramen', '71.56', 184, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sushi', '37.55', 52, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('bento box completo', '45.37', 194, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('gyudon', '52.92', 188, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('kombucha de gengibre', '12.18', 117, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('coquetel de lichia', '13.39', 118, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água', '30.46', 153, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água com gás', '18.69', 91, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('shochu com água quente', '31.43', 80, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá preto', '27.36', 152, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('leite de soja', '18.85', 66, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('saquê', '14.26', 165, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de ameixa japonesa', '34.55', 68, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de laranja', '27.15', 94, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de manga', '18.94', 131, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('saquê doce', '25.50', 136, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cerveja artesanal japonesa', '20.11', 153, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá de hortelã', '9.77', 52, 28);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ovos mexidos com chorizo', '50.03', 75, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chiles en nogada', '59.13', 155, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cochinita pibil', '69.91', 182, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chocolate quente com pão', '23.33', 138, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tamales', '46.47', 131, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tacos de pescado', '14.99', 105, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa azteca', '59.95', 74, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mole poblano', '20.11', 98, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('frutas frescas com limão e ch', '28.65', 155, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('feijão refrito', '74.86', 68, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('torta mexicana', '44.26', 89, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('huevos rancheros', '62.40', 78, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chile relleno', '16.35', 190, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('camarones a la diabla', '14.21', 183, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('quesadillas', '43.68', 123, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('carne asada', '46.99', 126, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de tortilla', '77.69', 185, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('arroz mexicano', '54.21', 61, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('torradas com guacamole', '59.91', 79, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('birria', '35.93', 150, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pan dulce', '50.87', 182, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('burritos de café da manhã', '53.94', 197, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ensalada de nopales', '44.88', 98, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('quesadillas de queijo', '51.84', 193, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de feijão', '22.41', 195, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de milho', '43.55', 176, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('enchiladas', '37.60', 104, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pozole', '35.13', 79, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tacos al pastor', '62.87', 63, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('michelada', '26.80', 102, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('margarita', '24.86', 84, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sangrita', '8.16', 138, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tequila', '31.81', 56, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('licor de café', '31.36', 173, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de laranja', '24.19', 181, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de maracujá', '29.88', 190, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mojito mexicano', '34.66', 149, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pulque', '32.62', 162, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('horchata', '10.28', 191, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de manga', '32.89', 103, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('jamaica (hibisco)', '19.66', 54, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mezcal', '8.29', 133, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de toranja', '33.47', 111, 23);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ovos mexidos com chorizo', '50.03', 75, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chiles en nogada', '59.13', 155, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cochinita pibil', '69.91', 182, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chocolate quente com pão', '23.33', 138, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tamales', '46.47', 131, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tacos de pescado', '14.99', 105, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa azteca', '59.95', 74, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mole poblano', '20.11', 98, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('frutas frescas com limão e ch', '28.65', 155, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('feijão refrito', '74.86', 68, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('torta mexicana', '44.26', 89, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('huevos rancheros', '62.40', 78, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chile relleno', '16.35', 190, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('camarones a la diabla', '14.21', 183, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('quesadillas', '43.68', 123, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('carne asada', '46.99', 126, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de tortilla', '77.69', 185, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('arroz mexicano', '54.21', 61, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('torradas com guacamole', '59.91', 79, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('birria', '35.93', 150, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pan dulce', '50.87', 182, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('burritos de café da manhã', '53.94', 197, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ensalada de nopales', '44.88', 98, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('quesadillas de queijo', '51.84', 193, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de feijão', '22.41', 195, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de milho', '43.55', 176, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('enchiladas', '37.60', 104, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pozole', '35.13', 79, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tacos al pastor', '62.87', 63, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('michelada', '26.80', 102, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('margarita', '24.86', 84, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sangrita', '8.16', 138, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tequila', '31.81', 56, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('licor de café', '31.36', 173, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de laranja', '24.19', 181, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de maracujá', '29.88', 190, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mojito mexicano', '34.66', 149, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pulque', '32.62', 162, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('horchata', '10.28', 191, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de manga', '32.89', 103, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('jamaica (hibisco)', '19.66', 54, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mezcal', '8.29', 133, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de toranja', '33.47', 111, 25);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ovos mexidos com chorizo', '50.03', 75, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chiles en nogada', '59.13', 155, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cochinita pibil', '69.91', 182, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chocolate quente com pão', '23.33', 138, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tamales', '46.47', 131, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tacos de pescado', '14.99', 105, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa azteca', '59.95', 74, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mole poblano', '20.11', 98, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('frutas frescas com limão e ch', '28.65', 155, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('feijão refrito', '74.86', 68, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('torta mexicana', '44.26', 89, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('huevos rancheros', '62.40', 78, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chile relleno', '16.35', 190, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('camarones a la diabla', '14.21', 183, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('quesadillas', '43.68', 123, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('carne asada', '46.99', 126, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de tortilla', '77.69', 185, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('arroz mexicano', '54.21', 61, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('torradas com guacamole', '59.91', 79, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('birria', '35.93', 150, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pan dulce', '50.87', 182, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('burritos de café da manhã', '53.94', 197, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('ensalada de nopales', '44.88', 98, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('quesadillas de queijo', '51.84', 193, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de feijão', '22.41', 195, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sopa de milho', '43.55', 176, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('enchiladas', '37.60', 104, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pozole', '35.13', 79, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tacos al pastor', '62.87', 63, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('michelada', '26.80', 102, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('margarita', '24.86', 84, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sangrita', '8.16', 138, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('tequila', '31.81', 56, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('licor de café', '31.36', 173, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de laranja', '24.19', 181, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de maracujá', '29.88', 190, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mojito mexicano', '34.66', 149, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('pulque', '32.62', 162, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('horchata', '10.28', 191, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de manga', '32.89', 103, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('jamaica (hibisco)', '19.66', 54, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mezcal', '8.29', 133, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de toranja', '33.47', 111, 26);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Arroz pegajoso com durião', '24.87', 169, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Frango ao molho de gengibre.', '79.42', 180, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Camarão empanado com molho de', '24.70', 153, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Frango com castanha de caju', '18.20', 151, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Tom Kha Gai', '39.25', 116, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Arroz frito tailandês', '66.22', 61, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Porco assado com molho de tam', '52.14', 152, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Pad Thai de camarão', '74.44', 186, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Almôndegas tailandesas com mo', '13.68', 165, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Carne marinada com pimenta e', '36.99', 142, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Peixe ao vapor com limão e er', '41.50', 149, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Costela de porco ao curry ma', '12.65', 98, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Curry vermelho de porco', '41.23', 103, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Pad Thai vegetariano', '29.29', 194, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Tortinha de coco', '50.22', 193, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Salada de macarrão de vidro', '38.51', 81, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Peixe frito com molho de tama', '41.00', 75, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Frango grelhado com molho pic', '52.66', 75, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Berinjela ao curry verde', '32.54', 97, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Panquecas tailandesas', '46.02', 146, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Curry amarelo de legumes', '58.30', 156, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Macarrão frito com manjericão', '79.00', 185, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Satay de frango', '68.51', 158, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Tom Yum', '40.47', 152, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Curry verde de frango', '40.48', 129, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Pato assado ao curry', '69.48', 186, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Bolinhos de arroz frito', '79.75', 76, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Arroz pegajoso com manga', '36.02', 144, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Porco agridoce', '23.18', 178, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Salada de mamão verde', '75.49', 151, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de maracujá', '17.71', 112, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de melancia', '33.03', 72, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cerveja Singha', '11.29', 127, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água de coco', '19.36', 186, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de manga', '33.53', 76, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('mojito tailandês', '31.13', 188, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('smoothie de coco', '13.73', 138, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cerveja Chang', '14.51', 68, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('sangria tailandesa com frutas', '27.78', 157, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('Margarita de manga com piment', '24.01', 54, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('cerveja Leo', '8.64', 166, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('suco de abacaxi', '30.47', 195, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('água', '15.85', 78, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('coquetel de lichia com vodka', '10.97', 181, 20);
INSERT INTO PRODUTO (nome, valor, estoque, id_dependencia) VALUES ('chá tailandês com leite (Cha ', '28.92', 99, 20);
