INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Hotel Vista do Sol', 'Chalé', 'Família', '97235-829', 2348); 
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Refúgio da Montanha', 'Pousada', 'Família', '57912-287', 381);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Oásis do Amanhecer', 'Hotel Fazenda', 'Adultos', '72765-467', 2725);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Pousada Serenidade', 'Pousada', 'Família', '53376-970', 6);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Château de Lumière', 'Resort', 'Adultos', '67334-159', 522);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Hotel Safari Dreams', 'Tradicional', 'Pet-friendly', '21782-188', 1574);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Paraíso das Palmeiras', 'Tradicional', 'Beira-Mar', '20894-558', 964);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Diamante Azul Hotel', 'Tradicional', 'Trabalho', '76588-618', 775);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Ilha do Descanso', 'Resort', 'Beira-Mar', '96706-703', 30);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Vila Tropical Escape', 'Hotel Fazenda', 'Pet-friendly', '25601-957', 561);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Encanto Urbano', 'Tradicional', 'Trabalho', '84241-931', 3);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Floresta Encantada Lodge', 'Chalé', 'Adultos', '64461-574', 305);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Estalagem do Pôr do Sol', 'Pousada', 'Família', '36640-960', 2995);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Grand Harmonia', 'Resort', 'Luxo', '81709-549', 1286);
INSERT INTO UNIDADE (nome_fantasia, tipo, setor, cep, numero) VALUES ('Jardins do Éden', 'Resort', 'Luxo', '43062-063', 541);